#!/usr/bin/env python3
"""Export an editable SVG package to native PPTX.

This adapter uses the vendored SVG -> DrawingML converter in this skill. It
exists because importing an SVG into PowerPoint and then using "Convert to
Shape" lets PowerPoint reinterpret SVG text layout on its own, which often
breaks CJK text positioning. The native converter writes DrawingML directly, so
text boxes, pictures, and primitives land in PPTX coordinates without going
through PowerPoint's SVG parser.
"""

from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path
from xml.etree import ElementTree as ET


SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def _is_math_svg_node(elem: ET.Element, removable_ids: set[str]) -> bool:
    if not removable_ids:
        return False
    elem_id = elem.get("id")
    if elem_id not in removable_ids:
        return False
    class_tokens = set((elem.get("class") or "").split())
    return bool(elem.get("data-latex") or class_tokens.intersection({"math", "formula"}))


def _copy_svg_without_math_groups(source: Path, dest: Path, removable_ids: set[str]) -> None:
    """Copy *source* SVG while removing successfully converted formula groups."""
    if not removable_ids:
        shutil.copy2(source, dest)
        return

    tree = ET.parse(source)
    root = tree.getroot()

    def prune(parent: ET.Element) -> None:
        for child in list(parent):
            if _is_math_svg_node(child, removable_ids):
                parent.remove(child)
            else:
                prune(child)

    prune(root)
    tree.write(dest, encoding="utf-8", xml_declaration=True)


def _math_report_path(output_path: Path) -> Path:
    return output_path.with_name(output_path.name + ".math_report.json")


def _write_math_report(path: Path, report: dict) -> None:
    serializable = {k: v for k, v in report.items() if k != "prepared"}
    path.write_text(json.dumps(serializable, ensure_ascii=False, indent=2), encoding="utf-8")


def export_native_pptx(
    svg_path: Path,
    package_dir: Path,
    output_path: Path,
    trace_path: Path | None = None,
    verbose: bool = False,
) -> Path:
    """Create a single-slide native PPTX from *svg_path*.

    Args:
        svg_path: The SVG generated by this skill.
        package_dir: Directory containing the SVG package, especially assets/.
        output_path: Destination .pptx path.
        trace_path: Optional conversion trace JSON path.
        verbose: Print native converter progress.

    Returns:
        The written output_path.
    """
    svg_path = svg_path.resolve()
    package_dir = package_dir.resolve()
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    from svg_to_pptx.pptx_builder import create_pptx_with_native_svg  # type: ignore
    from pptx_math import prepare_editable_math, patch_pptx_with_prepared_math  # type: ignore

    manifest_path = package_dir / "manifest.json"
    math_report_path = _math_report_path(output_path)
    prepared_math: dict | None = None
    removable_math_ids: set[str] = set()
    if manifest_path.exists():
        try:
            prepared_math = prepare_editable_math(manifest_path)
            removable_math_ids = {
                str(item.get("id"))
                for item in prepared_math.get("prepared", [])
                if item.get("id")
            }
        except Exception as exc:
            prepared_math = {
                "status": "failed",
                "attempted_count": 0,
                "prepared_count": 0,
                "editable_count": 0,
                "fallback_vector_count": 0,
                "failures": [{"id": "pptx-math-preflight", "message": repr(exc)}],
            }

    with tempfile.TemporaryDirectory(prefix="i2svg_pptx_") as tmp:
        project_dir = Path(tmp)
        svg_output = project_dir / "svg_output"
        svg_output.mkdir(parents=True, exist_ok=True)
        staged_svg = svg_output / "01_editable.svg"
        _copy_svg_without_math_groups(svg_path, staged_svg, removable_math_ids)

        assets_src = package_dir / "assets"
        if assets_src.exists():
            shutil.copytree(assets_src, project_dir / "assets")

        def run_converter(input_svg: Path) -> bool:
            return create_pptx_with_native_svg(
                svg_files=[input_svg],
                output_path=output_path,
                canvas_format=None,
                verbose=verbose,
                transition=None,
                use_native_shapes=True,
                animation=None,
                enable_notes=False,
                conversion_trace_path=trace_path,
            )

        ok = run_converter(staged_svg)
        if not ok or not output_path.exists():
            raise RuntimeError(f"native PPTX export failed: {output_path}")

        if prepared_math is not None:
            try:
                patch_pptx_with_prepared_math(
                    output_path,
                    prepared_math,
                    report_path=math_report_path,
                )
            except Exception as exc:
                # Keep the PPTX visually complete even if OMML injection fails.
                # Re-export from the original SVG so formula vectors are present.
                shutil.copy2(svg_path, staged_svg)
                ok = run_converter(staged_svg)
                if not ok or not output_path.exists():
                    raise RuntimeError(f"native PPTX recovery export failed: {output_path}") from exc
                attempted = int(prepared_math.get("attempted_count") or 0)
                failures = list(prepared_math.get("failures") or [])
                failures.append({"id": "pptx-math-patch", "message": repr(exc)})
                _write_math_report(
                    math_report_path,
                    {
                        "status": "failed",
                        "attempted_count": attempted,
                        "prepared_count": int(prepared_math.get("prepared_count") or 0),
                        "editable_count": 0,
                        "fallback_vector_count": attempted,
                        "office_math_xml_count": 0,
                        "mml2omml_xsl": prepared_math.get("mml2omml_xsl"),
                        "failures": failures,
                    },
                )

    return output_path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("svg", type=Path)
    parser.add_argument("--package-dir", type=Path, default=None)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--trace", type=Path, default=None)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    package_dir = args.package_dir or args.svg.parent
    out = export_native_pptx(
        args.svg,
        package_dir,
        args.out,
        trace_path=args.trace,
        verbose=args.verbose,
    )
    print(f"PPTX written to: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
